{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "80fad0bb-c371-4bcf-b1f2-f5af281e8813",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2024-06-03 19:36:10,187 Starting Bokeh server version 3.4.1 (running on Tornado 6.3.3)\n",
      "2024-06-03 19:36:10,188 Host wildcard '*' will allow connections originating from multiple (or possibly all) hostnames or IPs. Use non-wildcard values to restrict access explicitly\n",
      "2024-06-03 19:36:10,189 User authentication hooks NOT provided (default user enabled)\n",
      "2024-06-03 19:36:10,192 Bokeh app running at: http://0.0.0.0:5000/app\n",
      "2024-06-03 19:36:10,192 Starting Bokeh server with process id: 58847\n",
      "BokehDeprecationWarning: 'tile_providers module' was deprecated in Bokeh 3.0.0 and will be removed, use 'add_tile directly' instead.\n",
      "BokehDeprecationWarning: 'get_provider' was deprecated in Bokeh 3.0.0 and will be removed, use 'add_tile directly' instead.\n",
      "BokehDeprecationWarning: 'circle() method with size value' was deprecated in Bokeh 3.4.0 and will be removed, use 'scatter(size=...) instead' instead.\n",
      "2024-06-03 19:36:12,331 WebSocket connection opened\n",
      "2024-06-03 19:36:12,332 ServerConnection created\n"
     ]
    }
   ],
   "source": [
    "!panel serve app.py --allow-websocket-origin=* --port 5000 --address 0.0.0.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "3ee29d26-c6fb-4dba-b461-7de9433f1398",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2024-05-24 11:08:18,871 Starting Bokeh server version 3.4.1 (running on Tornado 6.3.3)\n",
      "2024-05-24 11:08:18,872 User authentication hooks NOT provided (default user enabled)\n",
      "2024-05-24 11:08:18,876 Bokeh app running at: http://0.0.0.0:5000/app\n",
      "2024-05-24 11:08:18,876 Starting Bokeh server with process id: 48418\n",
      "Creating map figure...\n",
      "Using tile source URL: https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png\n",
      "Tile source added to plot.\n",
      "2024-05-24 11:08:20,155 WebSocket connection opened\n",
      "2024-05-24 11:08:20,156 ServerConnection created\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 11.0 date_begin= 2024-04-24 date_end= 2024-05-24 scale= 30 min station_amount= 1\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|███████████████████████████████████| 2880/2880 [00:00<00:00, 689356.59it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:08:27,053 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2024-04-24 date_end= 2024-05-24 scale= 30 min station_amount= 1\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|███████████████████████████████████| 2880/2880 [00:00<00:00, 474007.04it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:08:50,838 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2024-04-24 date_end= 2024-05-24 scale= 30 min station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|███████████████████████████████████| 2880/2880 [00:00<00:00, 813386.00it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:09:02,185 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2024-02-01 date_end= 2024-05-24 scale= 1 vecka station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|█████████████████████████████████| 10848/10848 [00:00<00:00, 888355.85it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:09:21,193 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2024-05-24 date_end= 2024-05-24 scale= 1 vecka station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "2024-05-24 11:09:38,399 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Samma start och slutdatum')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 134, in run_program\n",
      "    start_stop_list = rain_data.divide_time(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/rain_data.py\", line 160, in divide_time\n",
      "    raise ValueError(\"Samma start och slutdatum\")\n",
      "ValueError: Samma start och slutdatum\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2025-04-02 date_end= 2024-05-24 scale= 1 vecka station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "2024-05-24 11:09:53,750 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Slutdatum senare än startdatum')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 134, in run_program\n",
      "    start_stop_list = rain_data.divide_time(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/rain_data.py\", line 157, in divide_time\n",
      "    raise ValueError(\"Slutdatum senare än startdatum\")\n",
      "ValueError: Slutdatum senare än startdatum\n",
      "got here\n",
      "auth_token= 64880c14af3bb0dcb503dd5b|7d6b45c38305aa54b0e0471cdb96d857 latitude= 12.0 longitude= 59.0 date_begin= 2023-03-01 date_end= 2024-05-24 scale= 1 vecka station_amount= 5\n",
      "got here 2222222222222222222222! \n",
      "\n",
      "got here?\n",
      "got here!\n",
      "100%|█████████████████████████████████| 43200/43200 [00:00<00:00, 477179.00it/s]\n",
      "0it [00:00, ?it/s]\n",
      "[]\n",
      "2024-05-24 11:10:08,591 error handling message\n",
      " message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p1089'}]]}}}]} \n",
      " error: ValueError('Ingen data kunde hittas vid skapande av datavy. \\nDetta kan bland annat hända om vald period är kortar än valt tidssteg.')\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 249, in format_median_data_view\n",
      "    median_view_df = pd.DataFrame(median_array, columns=[\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/frame.py\", line 722, in __init__\n",
      "    mgr = ndarray_to_mgr(\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 349, in ndarray_to_mgr\n",
      "    _check_values_indices_shape_match(values, index, columns)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/pandas/core/internals/construction.py\", line 416, in _check_values_indices_shape_match\n",
      "    raise ValueError(\"Empty data passed with indices specified.\")\n",
      "ValueError: Empty data passed with indices specified.\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/protocol_handler.py\", line 97, in handle\n",
      "    work = await handler(message, connection)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 94, in _needs_document_lock_wrapper\n",
      "    result = func(self, *args, **kwargs)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/server/session.py\", line 286, in _handle_patch\n",
      "    message.apply_to_document(self.document, self)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in apply_to_document\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/protocol/messages/patch_doc.py\", line 104, in <lambda>\n",
      "    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/document.py\", line 391, in apply_json_patch\n",
      "    DocumentPatchedEvent.handle_event(self, event, setter)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 245, in handle_event\n",
      "    event_cls._handle_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/events.py\", line 280, in _handle_event\n",
      "    cb(event.msg_data)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 390, in trigger_event\n",
      "    model._trigger_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 113, in _trigger_event\n",
      "    self.document.callbacks.notify_event(cast(Model, self), event, invoke)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 260, in notify_event\n",
      "    invoke_with_curdoc(doc, callback_invoker)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/document/callbacks.py\", line 443, in invoke_with_curdoc\n",
      "    return f()\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/bokeh/util/callback_manager.py\", line 109, in invoke\n",
      "    cast(EventCallbackWithEvent, callback)(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 498, in _server_event\n",
      "    self._comm_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 485, in _comm_event\n",
      "    state._handle_exception(e)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/state.py\", line 458, in _handle_exception\n",
      "    raise exception\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 483, in _comm_event\n",
      "    self._process_bokeh_event(doc, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/reactive.py\", line 420, in _process_bokeh_event\n",
      "    self._process_event(event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/widgets/button.py\", line 243, in _process_event\n",
      "    self.clicks += 1\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 528, in _f\n",
      "    instance_param.__set__(obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameters.py\", line 543, in __set__\n",
      "    super().__set__(obj,val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 530, in _f\n",
      "    return f(self, obj, val)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 1552, in __set__\n",
      "    obj.param._call_watcher(watcher, event)\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2525, in _call_watcher\n",
      "    self_._execute_watcher(watcher, (event,))\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/param/parameterized.py\", line 2505, in _execute_watcher\n",
      "    watcher.fn(*args, **kwargs)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 116, in submit\n",
      "    output_file = run_program(input_data)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/backend_handler.py\", line 137, in run_program\n",
      "    df1, df2, df3 = data_processing.create_data_views_for_excel(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 478, in create_data_views_for_excel\n",
      "    median_df = format_median_data_view(\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/back_end/data_processing.py\", line 256, in format_median_data_view\n",
      "    raise ValueError(\"Ingen data kunde hittas vid skapande av datavy. \\n\"\n",
      "ValueError: Ingen data kunde hittas vid skapande av datavy. \n",
      "Detta kan bland annat hända om vald period är kortar än valt tidssteg.\n",
      "^C\n",
      "\n",
      "Interrupted, shutting down\n"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4e7ec546-f85a-43dc-9736-5ce0aef62e8f",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    },
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2024-05-24 09:41:02,443 Starting Bokeh server version 3.4.1 (running on Tornado 6.3.3)\n",
      "2024-05-24 09:41:02,445 User authentication hooks NOT provided (default user enabled)\n",
      "2024-05-24 09:41:02,448 Bokeh app running at: http://0.0.0.0:5000/app\n",
      "2024-05-24 09:41:02,448 Starting Bokeh server with process id: 46838\n",
      "2024-05-24 09:41:17,268 Error running application handler <panel.io.handlers.ScriptHandler object at 0x7f3c6b1eb310>: No module named 'widgets'\n",
      "File 'app.py', line 6, in <module>:\n",
      "from widgets.signal_selection_widget import SignalSelectionWidget Traceback (most recent call last):\n",
      "  File \"/opt/app-root/lib64/python3.9/site-packages/panel/io/handlers.py\", line 358, in run\n",
      "    exec(self._code, module.__dict__)\n",
      "  File \"/opt/app-root/src/gitnetatmopanel/app.py\", line 6, in <module>\n",
      "    from widgets.signal_selection_widget import SignalSelectionWidget\n",
      "ModuleNotFoundError: No module named 'widgets'\n",
      " \n",
      "2024-05-24 09:41:17,506 WebSocket connection opened\n",
      "2024-05-24 09:41:17,507 ServerConnection created\n",
      "^C\n",
      "\n",
      "Interrupted, shutting down\n"
     ]
    }
   ],
   "source": [
    "!panel serve app.py --allow-websocket-origin=\"t-app1-560ip-berakning-test.apps.ocpint.gbgpaas.se\" --port 5000 --address 0.0.0.0 #-basic-auth credentials.json #--logout-template templates/login.html #--basic-login-template templates/login.html --cookie-secret my_super_safe_cookie_secret\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "baf3c500-dad7-4e71-b23c-b6e277cfba89",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "!panel serve app.py --allow-websocket-origin=\"t-app2-560ip-berakning-test.apps.ocpint.gbgpaas.se\" --port 8080 --address 0.0.0.0 --admin"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "id": "3a05a75f-fdef-42fd-8e9c-7ca1776e0f45",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting panel==1.4\n",
      "  Downloading panel-1.4.0-py3-none-any.whl (24.6 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m24.6/24.6 MB\u001b[0m \u001b[31m9.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m:00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hCollecting bokeh==3.4.1\n",
      "  Downloading bokeh-3.4.1-py3-none-any.whl (7.0 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m7.0/7.0 MB\u001b[0m \u001b[31m174.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: jinja2==3.0 in /opt/app-root/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (3.0.0)\n",
      "Requirement already satisfied: ipython-sql in /opt/app-root/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (0.5.0)\n",
      "Requirement already satisfied: openpyxl in /opt/app-root/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (3.1.2)\n",
      "Requirement already satisfied: folium in /opt/app-root/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (0.16.0)\n",
      "Requirement already satisfied: psycopg2 in /opt/app-root/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2.9.9)\n",
      "Requirement already satisfied: xyzservices>=2021.09.1 in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (2023.7.0)\n",
      "Collecting param<3.0,>=2.0.0\n",
      "  Downloading param-2.1.0-py3-none-any.whl (116 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m116.6/116.6 kB\u001b[0m \u001b[31m271.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hRequirement already satisfied: mdit-py-plugins in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (0.4.0)\n",
      "Requirement already satisfied: tqdm>=4.48.0 in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (4.66.1)\n",
      "Requirement already satisfied: requests in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (2.31.0)\n",
      "Requirement already satisfied: linkify-it-py in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (2.0.3)\n",
      "Requirement already satisfied: bleach in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (6.0.0)\n",
      "Requirement already satisfied: markdown-it-py in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (3.0.0)\n",
      "Requirement already satisfied: pandas>=1.2 in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (1.5.3)\n",
      "Requirement already satisfied: typing-extensions in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (4.8.0)\n",
      "Requirement already satisfied: pyviz-comms>=2.0.0 in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (3.0.2)\n",
      "Requirement already satisfied: markdown in /opt/app-root/lib/python3.9/site-packages (from panel==1.4->-r requirements.txt (line 1)) (3.6)\n",
      "Requirement already satisfied: tornado>=6.2 in /opt/app-root/lib/python3.9/site-packages (from bokeh==3.4.1->-r requirements.txt (line 2)) (6.3.3)\n",
      "Requirement already satisfied: numpy>=1.16 in /opt/app-root/lib/python3.9/site-packages (from bokeh==3.4.1->-r requirements.txt (line 2)) (1.24.4)\n",
      "Requirement already satisfied: packaging>=16.8 in /opt/app-root/lib/python3.9/site-packages (from bokeh==3.4.1->-r requirements.txt (line 2)) (23.1)\n",
      "Requirement already satisfied: contourpy>=1.2 in /opt/app-root/lib/python3.9/site-packages (from bokeh==3.4.1->-r requirements.txt (line 2)) (1.2.1)\n",
      "Requirement already satisfied: PyYAML>=3.10 in /opt/app-root/lib/python3.9/site-packages (from bokeh==3.4.1->-r requirements.txt (line 2)) (6.0.1)\n",
      "Requirement already satisfied: pillow>=7.1.0 in /opt/app-root/lib/python3.9/site-packages (from bokeh==3.4.1->-r requirements.txt (line 2)) (10.0.1)\n",
      "Requirement already satisfied: MarkupSafe>=2.0.0rc2 in /opt/app-root/lib/python3.9/site-packages (from jinja2==3.0->-r requirements.txt (line 3)) (2.1.3)\n",
      "Requirement already satisfied: sqlalchemy>=2.0 in /opt/app-root/lib/python3.9/site-packages (from ipython-sql->-r requirements.txt (line 4)) (2.0.29)\n",
      "Requirement already satisfied: ipython in /opt/app-root/lib/python3.9/site-packages (from ipython-sql->-r requirements.txt (line 4)) (8.15.0)\n",
      "Requirement already satisfied: six in /opt/app-root/lib/python3.9/site-packages (from ipython-sql->-r requirements.txt (line 4)) (1.16.0)\n",
      "Requirement already satisfied: prettytable in /opt/app-root/lib/python3.9/site-packages (from ipython-sql->-r requirements.txt (line 4)) (3.10.0)\n",
      "Requirement already satisfied: sqlparse in /opt/app-root/lib/python3.9/site-packages (from ipython-sql->-r requirements.txt (line 4)) (0.5.0)\n",
      "Requirement already satisfied: ipython-genutils in /opt/app-root/lib/python3.9/site-packages (from ipython-sql->-r requirements.txt (line 4)) (0.2.0)\n",
      "Requirement already satisfied: et-xmlfile in /opt/app-root/lib/python3.9/site-packages (from openpyxl->-r requirements.txt (line 5)) (1.1.0)\n",
      "Requirement already satisfied: branca>=0.6.0 in /opt/app-root/lib/python3.9/site-packages (from folium->-r requirements.txt (line 6)) (0.7.2)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /opt/app-root/lib/python3.9/site-packages (from pandas>=1.2->panel==1.4->-r requirements.txt (line 1)) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/app-root/lib/python3.9/site-packages (from pandas>=1.2->panel==1.4->-r requirements.txt (line 1)) (2023.3.post1)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /opt/app-root/lib/python3.9/site-packages (from sqlalchemy>=2.0->ipython-sql->-r requirements.txt (line 4)) (3.0.3)\n",
      "Requirement already satisfied: webencodings in /opt/app-root/lib/python3.9/site-packages (from bleach->panel==1.4->-r requirements.txt (line 1)) (0.5.1)\n",
      "Requirement already satisfied: pickleshare in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (0.7.5)\n",
      "Requirement already satisfied: jedi>=0.16 in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (0.19.0)\n",
      "Requirement already satisfied: backcall in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (0.2.0)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (3.0.39)\n",
      "Requirement already satisfied: pygments>=2.4.0 in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (2.16.1)\n",
      "Requirement already satisfied: exceptiongroup in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (1.1.3)\n",
      "Requirement already satisfied: pexpect>4.3 in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (4.8.0)\n",
      "Requirement already satisfied: traitlets>=5 in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (5.10.0)\n",
      "Requirement already satisfied: decorator in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (5.1.1)\n",
      "Requirement already satisfied: stack-data in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (0.6.2)\n",
      "Requirement already satisfied: matplotlib-inline in /opt/app-root/lib/python3.9/site-packages (from ipython->ipython-sql->-r requirements.txt (line 4)) (0.1.6)\n",
      "Requirement already satisfied: uc-micro-py in /opt/app-root/lib/python3.9/site-packages (from linkify-it-py->panel==1.4->-r requirements.txt (line 1)) (1.0.3)\n",
      "Requirement already satisfied: importlib-metadata>=4.4 in /opt/app-root/lib/python3.9/site-packages (from markdown->panel==1.4->-r requirements.txt (line 1)) (6.8.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in /opt/app-root/lib/python3.9/site-packages (from markdown-it-py->panel==1.4->-r requirements.txt (line 1)) (0.1.2)\n",
      "Requirement already satisfied: wcwidth in /opt/app-root/lib/python3.9/site-packages (from prettytable->ipython-sql->-r requirements.txt (line 4)) (0.2.6)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /opt/app-root/lib/python3.9/site-packages (from requests->panel==1.4->-r requirements.txt (line 1)) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /opt/app-root/lib/python3.9/site-packages (from requests->panel==1.4->-r requirements.txt (line 1)) (2023.7.22)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/app-root/lib/python3.9/site-packages (from requests->panel==1.4->-r requirements.txt (line 1)) (1.26.16)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /opt/app-root/lib/python3.9/site-packages (from requests->panel==1.4->-r requirements.txt (line 1)) (3.2.0)\n",
      "Requirement already satisfied: zipp>=0.5 in /opt/app-root/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown->panel==1.4->-r requirements.txt (line 1)) (3.17.0)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.3 in /opt/app-root/lib/python3.9/site-packages (from jedi>=0.16->ipython->ipython-sql->-r requirements.txt (line 4)) (0.8.3)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /opt/app-root/lib/python3.9/site-packages (from pexpect>4.3->ipython->ipython-sql->-r requirements.txt (line 4)) (0.7.0)\n",
      "Requirement already satisfied: asttokens>=2.1.0 in /opt/app-root/lib/python3.9/site-packages (from stack-data->ipython->ipython-sql->-r requirements.txt (line 4)) (2.4.0)\n",
      "Requirement already satisfied: executing>=1.2.0 in /opt/app-root/lib/python3.9/site-packages (from stack-data->ipython->ipython-sql->-r requirements.txt (line 4)) (1.2.0)\n",
      "Requirement already satisfied: pure-eval in /opt/app-root/lib/python3.9/site-packages (from stack-data->ipython->ipython-sql->-r requirements.txt (line 4)) (0.2.2)\n",
      "Installing collected packages: param, bokeh, panel\n",
      "  Attempting uninstall: param\n",
      "    Found existing installation: param 1.13.0\n",
      "    Uninstalling param-1.13.0:\n",
      "      Successfully uninstalled param-1.13.0\n",
      "  Attempting uninstall: bokeh\n",
      "    Found existing installation: bokeh 2.0.0\n",
      "    Uninstalling bokeh-2.0.0:\n",
      "      Successfully uninstalled bokeh-2.0.0\n",
      "  Attempting uninstall: panel\n",
      "    Found existing installation: panel 0.9.4\n",
      "    Uninstalling panel-0.9.4:\n",
      "      Successfully uninstalled panel-0.9.4\n",
      "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "holoviews 1.13.2 requires param<2.0,>=1.9.3, but you have param 2.1.0 which is incompatible.\u001b[0m\u001b[31m\n",
      "\u001b[0mSuccessfully installed bokeh-3.4.1 panel-1.4.0 param-2.1.0\n",
      "\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m A new release of pip available: \u001b[0m\u001b[31;49m22.2.2\u001b[0m\u001b[39;49m -> \u001b[0m\u001b[32;49m24.0\u001b[0m\n",
      "\u001b[1m[\u001b[0m\u001b[34;49mnotice\u001b[0m\u001b[1;39;49m]\u001b[0m\u001b[39;49m To update, run: \u001b[0m\u001b[32;49mpip install --upgrade pip\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip install -r requirements.txt"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99f00a49-842a-48f3-ad78-9fafa7190904",
   "metadata": {},
   "outputs": [],
   "source": [
    "# tidigare dependencies\n",
    "#!pip install panel bokeh==3.3.4 ipython-sql openpyxl folium psycopg2\n",
    "#!pip install panel>=0.12.6 param>=1.12.0 pandas matplotlib"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
